spring:
  profiles:
    active: heroku
---
server:
  port: ${PORT}
spring:
  profiles: heroku
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PATH}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  #    connectionProperties: useUnicode=true;characterEncoding=utf-8;
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false